autoloader:
    default:
        recursive: false
        strict:    false
        basePath:  "/"
#    directories:
#        firstKey: 
#            dir: "some/directory/to/load"
#            strict: true
#            recursive: true
#        secondKey: 
#            dir: "/perl/some/other/directory/to/load"
